import { boolean, date, decimal, int, mysqlTable, serial, text, timestamp, unique } from 'drizzle-orm/mysql-core'

export const user = mysqlTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = mysqlTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }) })
export const account = mysqlTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = mysqlTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })

export const rentals = mysqlTable('rentals', { id: serial('id').primaryKey(), userId: text('userId').notNull(), contractNo: text('contractNo').notNull(), customerName: text('customerName').notNull(), customerPhone: text('customerPhone').notNull(), customerAddress: text('customerAddress'), deviceName: text('deviceName').notNull(), deviceType: text('deviceType').notNull().default('台式机'), deviceConfig: text('deviceConfig'), deviceCode: text('deviceCode'), cpu: text('cpu'), motherboard: text('motherboard'), memory: text('memory'), storage: text('storage'), graphicsCard: text('graphicsCard'), powerSupply: text('powerSupply'), caseModel: text('caseModel'), monitorInfo: text('monitorInfo'), screenSize: text('screenSize'), screenResolution: text('screenResolution'), refreshRate: text('refreshRate'), panelType: text('panelType'), ports: text('ports'), batteryInfo: text('batteryInfo'), adapterInfo: text('adapterInfo'), accessories: text('accessories'), colorGamut: text('colorGamut'), quantity: int('quantity').notNull().default(1), startDate: date('startDate', { mode: 'string' }).notNull(), endDate: date('endDate', { mode: 'string' }).notNull(), monthlyRent: decimal('monthlyRent', { precision: 12, scale: 2 }).notNull().default('0'), totalRent: decimal('totalRent', { precision: 12, scale: 2 }).notNull().default('0'), deposit: decimal('deposit', { precision: 12, scale: 2 }).notNull().default('0'), paidAmount: decimal('paidAmount', { precision: 12, scale: 2 }).notNull().default('0'), paymentStatus: text('paymentStatus').notNull().default('待收款'), status: text('status').notNull().default('在租'), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() }, (table) => [unique().on(table.userId, table.contractNo)])

export const rentalItems = mysqlTable('rental_items', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: int('rentalId').notNull(),
  deviceName: text('deviceName').notNull(), deviceType: text('deviceType').notNull().default('台式机'), deviceCode: text('deviceCode'), deviceConfig: text('deviceConfig'),
  quantity: int('quantity').notNull().default(1), startDate: date('startDate', { mode: 'string' }), endDate: date('endDate', { mode: 'string' }), monthlyRent: decimal('monthlyRent', { precision: 12, scale: 2 }).notNull().default('0'), totalRent: decimal('totalRent', { precision: 12, scale: 2 }).notNull().default('0'), boughtOutQuantity: int('boughtOutQuantity').notNull().default(0), returnedQuantity: int('returnedQuantity').notNull().default(0), lostQuantity: int('lostQuantity').notNull().default(0), buyoutAmount: decimal('buyoutAmount', { precision: 12, scale: 2 }).notNull().default('0'),
  cpu: text('cpu'), motherboard: text('motherboard'), memory: text('memory'), storage: text('storage'), graphicsCard: text('graphicsCard'), powerSupply: text('powerSupply'), caseModel: text('caseModel'), monitorInfo: text('monitorInfo'), screenSize: text('screenSize'), screenResolution: text('screenResolution'), refreshRate: text('refreshRate'), panelType: text('panelType'), ports: text('ports'), batteryInfo: text('batteryInfo'), adapterInfo: text('adapterInfo'), accessories: text('accessories'), colorGamut: text('colorGamut'),
  createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(),
})

export const buyoutRecords = mysqlTable('buyout_records', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: int('rentalId').notNull(), rentalItemId: int('rentalItemId').notNull(), quantity: int('quantity').notNull(), unitPrice: decimal('unitPrice', { precision: 12, scale: 2 }).notNull(), amount: decimal('amount', { precision: 12, scale: 2 }).notNull(), buyoutDate: date('buyoutDate', { mode: 'string' }).notNull(), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(),
})

export const renewalRecords = mysqlTable('renewal_records', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: int('rentalId').notNull(), sourceRentalItemId: int('sourceRentalItemId').notNull(), renewedRentalItemId: int('renewedRentalItemId').notNull(), quantity: int('quantity').notNull(), renewalMonths: int('renewalMonths'), billingUnit: text('billingUnit'), duration: int('duration'), unitPrice: decimal('unitPrice', { precision: 12, scale: 2 }), oldMonthlyRent: decimal('oldMonthlyRent', { precision: 12, scale: 2 }).notNull(), newMonthlyRent: decimal('newMonthlyRent', { precision: 12, scale: 2 }).notNull(), oldEndDate: date('oldEndDate', { mode: 'string' }).notNull(), newEndDate: date('newEndDate', { mode: 'string' }).notNull(), renewalAmount: decimal('renewalAmount', { precision: 12, scale: 2 }).notNull().default('0'), renewalDate: date('renewalDate', { mode: 'string' }).notNull(), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(),
})

export const paymentRecords = mysqlTable('payment_records', {
  id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: int('rentalId').notNull(), renewalRecordId: int('renewalRecordId'), buyoutRecordId: int('buyoutRecordId'), returnRecordId: int('returnRecordId'), lossRecordId: int('lossRecordId'), operatorName: text('operatorName'), amount: decimal('amount', { precision: 12, scale: 2 }).notNull(), paymentDate: date('paymentDate', { mode: 'string' }).notNull(), paymentMethod: text('paymentMethod').notNull(), feeType: text('feeType').notNull(), notes: text('notes'), createdAt: timestamp('createdAt').notNull().defaultNow(),
})

export const returnRecords = mysqlTable('return_records', { id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: int('rentalId').notNull(), rentalItemId: int('rentalItemId').notNull(), quantity: int('quantity').notNull(), returnDate: date('returnDate', { mode: 'string' }).notNull(), condition: text('condition').notNull(), deductionAmount: decimal('deductionAmount', { precision: 12, scale: 2 }).notNull().default('0'), depositRefund: decimal('depositRefund', { precision: 12, scale: 2 }).notNull().default('0'), notes: text('notes'), operatorName: text('operatorName').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const lossRecords = mysqlTable('loss_records', { id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: int('rentalId').notNull(), rentalItemId: int('rentalItemId').notNull(), quantity: int('quantity').notNull(), lossDate: date('lossDate', { mode: 'string' }).notNull(), unitCompensation: decimal('unitCompensation', { precision: 12, scale: 2 }).notNull(), amount: decimal('amount', { precision: 12, scale: 2 }).notNull(), notes: text('notes'), operatorName: text('operatorName').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const businessSettings = mysqlTable('business_settings', { id: serial('id').primaryKey(), userId: text('userId').notNull().unique(), lessorType: text('lessorType').notNull().default('企业'), lessorName: text('lessorName').notNull().default(''), identityNo: text('identityNo'), contactName: text('contactName'), phone: text('phone'), address: text('address'), paymentInfo: text('paymentInfo'), contractTerms: text('contractTerms'), themeMode: text('themeMode').notNull().default('system'), themeColor: text('themeColor').notNull().default('green'), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const contractSnapshots = mysqlTable('contract_snapshots', { id: serial('id').primaryKey(), userId: text('userId').notNull(), rentalId: int('rentalId').notNull().unique(), customerType: text('customerType').notNull().default('个人'), customerIdentityNo: text('customerIdentityNo'), customerCompany: text('customerCompany'), customerCreditCode: text('customerCreditCode'), lessorJson: text('lessorJson').notNull(), customerJson: text('customerJson').notNull(), itemsJson: text('itemsJson').notNull(), terms: text('terms').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const organizationMembers = mysqlTable('organization_members', { id: serial('id').primaryKey(), ownerId: text('ownerId').notNull(), memberUserId: text('memberUserId').notNull().unique(), role: text('role').notNull().default('employee'), active: boolean('active').notNull().default(true), permissions: text('permissions').notNull().default('rentals'), updatedAt: timestamp('updatedAt').notNull().defaultNow() })

export type Rental = typeof rentals.$inferSelect
export type RentalItem = typeof rentalItems.$inferSelect
export type BuyoutRecord = typeof buyoutRecords.$inferSelect
export type RenewalRecord = typeof renewalRecords.$inferSelect
export type PaymentRecord = typeof paymentRecords.$inferSelect
