'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { Banknote, CalendarPlus, CircleDollarSign, RefreshCw, Settings2, Wrench, X } from 'lucide-react'
import { toast } from 'sonner'
import { collectBillPayment, generateBills, recordLifecycle, type LifecycleInput } from '@/app/actions/lifecycle'

type Bill={id:number;billNo:string;periodStart:string;periodEnd:string;billType:string;amount:string;paidAmount:string;status:string}
type Event={id:number;eventType:string;eventDate:string;status:string;reason:string|null;notes:string|null}
type Item={id:number;deviceName:string;deviceCode:string|null;deviceConfig:string|null;monthlyRent:string}
type Rental={id:number;items:Item[];receivableBills?:Bill[];rentalEvents?:Event[]}
const money=(value:number|string)=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:0}).format(Number(value))
const today=()=>new Date().toISOString().slice(0,10)

export function LifecyclePanel({rental}:{rental:Rental}){
  const router=useRouter();const[pending,start]=useTransition();const[mode,setMode]=useState<'payment'|'deposit'|'replace'|'change'|'repair'|null>(null)
  const bills=rental.receivableBills||[];const events=rental.rentalEvents||[]
  const run=(work:()=>Promise<void>,message:string)=>start(async()=>{try{await work();toast.success(message);setMode(null);router.refresh()}catch(error){toast.error(error instanceof Error?error.message:'操作失败')}})
  return <>
    <section className="flex flex-col gap-3"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">月度应收账单</h3><p className="text-sm text-muted-foreground">收款自动按到期顺序核销</p></div>{!bills.length&&<button onClick={()=>run(()=>generateBills(rental.id),'应收账单已生成')} disabled={pending} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><CalendarPlus className="size-4"/>生成账单</button>}</div>
      {bills.length?<div className="flex flex-col gap-2">{bills.map(b=>{const due=Number(b.amount)-Number(b.paidAmount);return <div key={b.id} className="flex flex-col justify-between gap-2 rounded-xl border px-3 py-3 text-sm sm:flex-row sm:items-center"><div><p className="font-medium">{b.periodStart} 至 {b.periodEnd} · {b.billType}</p><p className="text-xs text-muted-foreground">{b.billNo}</p></div><div className="text-left sm:text-right"><p>{money(b.paidAmount)} / {money(b.amount)} · <span className={due>0?'text-accent':'text-primary'}>{b.status}</span></p>{due>0&&<p className="text-xs text-muted-foreground">待收 {money(due)}</p>}</div></div>})}</div>:<div className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">尚未生成应收账单</div>}
    </section>
    {events.length>0&&<section><h3 className="mb-3 font-semibold">设备与合同变更记录</h3><div className="flex flex-col gap-2">{events.map(e=><div key={e.id} className="flex justify-between gap-4 rounded-lg bg-muted px-3 py-2 text-sm"><span><strong>{e.eventType}</strong>{e.reason?` · ${e.reason}`:''}</span><span className="shrink-0 text-muted-foreground">{e.eventDate}</span></div>)}</div></section>}
    <div className="flex flex-wrap gap-2 border-t pt-4"><Action icon={<CircleDollarSign/>} label="登记收款" primary onClick={()=>setMode('payment')}/><Action icon={<Banknote/>} label="押金处理" onClick={()=>setMode('deposit')}/><Action icon={<RefreshCw/>} label="设备换机" onClick={()=>setMode('replace')}/><Action icon={<Settings2/>} label="配置/租金变更" onClick={()=>setMode('change')}/><Action icon={<Wrench/>} label="登记维修" onClick={()=>setMode('repair')}/></div>
    {mode&&<LifecycleDialog title={{payment:'登记收款',deposit:'押金处理',replace:'设备换机',change:'配置/租金变更',repair:'登记维修'}[mode]} onClose={()=>setMode(null)}><LifecycleForm mode={mode} rental={rental} pending={pending} submit={(data)=>{if(mode==='payment')run(()=>collectBillPayment(rental.id,Number(data.amount),data.eventDate,data.paymentMethod||'微信',data.notes),'收款已登记并核销');else run(()=>recordLifecycle({...data,rentalId:rental.id,eventType:{deposit:'押金处理',replace:'设备换机',change:'配置/租金变更',repair:'维修登记'}[mode] as LifecycleInput['eventType'],itemId:data.itemId?Number(data.itemId):undefined,amount:data.amount?Number(data.amount):undefined,monthlyRent:data.monthlyRent?Number(data.monthlyRent):undefined}),'业务操作已登记')}}/></LifecycleDialog>}
  </>
}
function Action({icon,label,onClick,primary=false}:{icon:React.ReactNode;label:string;onClick:()=>void;primary?:boolean}){return <button onClick={onClick} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-medium ${primary?'border-primary bg-primary text-primary-foreground':''}`}><span className="[&>svg]:size-4">{icon}</span>{label}</button>}
function LifecycleDialog({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/30 p-4"><div className="w-full max-w-lg rounded-xl border bg-card shadow-xl"><div className="flex items-center justify-between border-b p-4"><h3 className="font-semibold">{title}</h3><button aria-label="关闭" onClick={onClose}><X className="size-5"/></button></div><div className="p-4">{children}</div></div></div>}
function LifecycleForm({mode,rental,pending,submit}:{mode:string;rental:Rental;pending:boolean;submit:(data:any)=>void}){const[form,setForm]=useState<any>({eventDate:today(),paymentMethod:'微信',notes:'',reason:''});const set=(key:string,value:string)=>setForm((v:any)=>({...v,[key]:value}));const needsItem=['replace','change','repair'].includes(mode);return <form onSubmit={e=>{e.preventDefault();submit(form)}} className="flex flex-col gap-4">{needsItem&&<Select label="设备明细" value={form.itemId||''} onChange={v=>set('itemId',v)} options={rental.items.map(i=>[String(i.id),`${i.deviceName}${i.deviceCode?` · ${i.deviceCode}`:''}`])}/>}<Input label={mode==='payment'?'收款金额（元）':mode==='deposit'?'押金金额（退款请输入负数）':'发生日期'} type={['payment','deposit'].includes(mode)?'number':'date'} value={['payment','deposit'].includes(mode)?form.amount||'':form.eventDate} onChange={v=>set(['payment','deposit'].includes(mode)?'amount':'eventDate',v)}/>{['payment','deposit'].includes(mode)&&<Input label="业务日期" type="date" value={form.eventDate} onChange={v=>set('eventDate',v)}/>} {mode==='payment'&&<Select label="收款方式" value={form.paymentMethod} onChange={v=>set('paymentMethod',v)} options={['微信','支付宝','银行卡','现金','其他'].map(v=>[v,v])}/>} {mode==='replace'&&<><Input label="新设备名称" value={form.deviceName||''} onChange={v=>set('deviceName',v)}/><Input label="新设备编号" value={form.deviceCode||''} onChange={v=>set('deviceCode',v)}/></>} {mode==='change'&&<><Input label="新配置" value={form.deviceConfig||''} onChange={v=>set('deviceConfig',v)}/><Input label="新月租（元）" type="number" value={form.monthlyRent||''} onChange={v=>set('monthlyRent',v)}/></>} {mode==='repair'&&<><Input label="故障描述" value={form.faultDescription||''} onChange={v=>set('faultDescription',v)}/><Input label="处理结果" value={form.resolution||''} onChange={v=>set('resolution',v)}/><Input label="维修成本（元）" type="number" value={form.amount||''} onChange={v=>set('amount',v)}/></>}<Input label="原因/说明" value={form.reason||''} onChange={v=>set('reason',v)}/><Input label="备注" value={form.notes||''} onChange={v=>set('notes',v)}/><button disabled={pending} className="h-10 rounded-lg bg-primary font-medium text-primary-foreground disabled:opacity-60">{pending?'正在保存':'确认登记'}</button></form>}
function Input({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="flex flex-col gap-2 text-sm font-medium">{label}<input required={label!=='备注'} type={type} value={value} onChange={e=>onChange(e.target.value)} className="h-10 rounded-lg border bg-background px-3"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label className="flex flex-col gap-2 text-sm font-medium">{label}<select required value={value} onChange={e=>onChange(e.target.value)} className="h-10 rounded-lg border bg-background px-3"><option value="">请选择</option>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>}
